# Do not modify this file manually after generating it with nixos-generate-config.
#
# This file is included as a generic example for this repository template.
# For a real installation, generate your own hardware configuration with:
#
#   sudo nixos-generate-config --root /mnt
#
# Then review the generated file before committing it.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "uhci_hcd"
    "ehci_pci"
    "ahci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];

  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    # Generic disk label used to avoid exposing real disk UUIDs.
    #
    # If your root partition does not use this label, replace this value with
    # the device path generated by nixos-generate-config.
    #
    # Example generated value:
    # device = "/dev/disk/by-uuid/<your-root-partition-uuid>";
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    # Generic EFI partition label used to avoid exposing real disk UUIDs.
    #
    # If your EFI partition does not use this label, replace this value with
    # the device path generated by nixos-generate-config.
    #
    # Example generated value:
    # device = "/dev/disk/by-uuid/<your-efi-partition-uuid>";
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
